export const HTTP_CLIENT_PORT = 'HTTP_CLIENT_PORT';
export const PROXY_MANAGER_PORT = 'PROXY_MANAGER_PORT';
export const CACHE_PORT = 'CACHE_PORT';
export const GENERIC_SCRAPER = 'GENERIC_SCRAPER';
export const STORE_SCRAPER_FACTORY_PORT = 'STORE_SCRAPER_FACTORY_PORT';
